// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

import { ReactNode } from "react";
import { AppLayout } from "@/smartspecs/lib/presentation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
